// Vercel Function: /api/portal-data?token=...
// Verifies the signed token, returns the client data for that email.
// Data source: the deployed /data/portal/<slug>.json (pre-generated by ~/.claude/bin/portal-data-export.sh)
// Pre-generated files are public-but-unguessable (slug = sha256 of email).
import crypto from 'crypto';

function verify(token, secret) {
  const [body, sig] = (token || '').split('.');
  if (!body || !sig) return null;
  const expected = crypto.createHmac('sha256', secret).update(body).digest('base64url');
  if (sig !== expected) return null;
  try {
    const payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf-8'));
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) return null;
    return payload;
  } catch (e) { return null; }
}

export default async function handler(req, res) {
  const { token } = req.query;
  if (!token) return res.status(400).json({ ok: false, error: 'missing_token' });
  const secret = process.env.PORTAL_SECRET;
  if (!secret) return res.status(503).json({ ok: false, error: 'not_configured' });
  const payload = verify(token, secret);
  if (!payload) return res.status(401).json({ ok: false, error: 'invalid_token' });

  const slug = crypto.createHash('sha256').update(payload.email).digest('hex').slice(0, 32);
  // Fetch portal data from same-origin
  const proto = req.headers['x-forwarded-proto'] || 'https';
  const host = req.headers.host;
  const r = await fetch(`${proto}://${host}/data/portal/${slug}.json`);
  if (!r.ok) return res.status(404).json({ ok: false, error: 'not_found' });
  const data = await r.json();
  return res.status(200).json({ ok: true, email: payload.email, data });
}
